-- ############################################################################
-- ⛔ FILE CHẾT — ĐỪNG CHẠY. Cập nhật 10/09/2026.
--
-- Sổ địa chỉ ĐÃ QUAY LẠI theo UC-USER-05 (Khu vực 2): app/models/AddressModel.php
-- đọc và ghi bảng `addresses` trở lại, và trang Hồ sơ hiện danh sách địa chỉ
-- lấy thẳng từ đó. Chạy file này bây giờ là XOÁ SỔ ĐỊA CHỈ CỦA MỌI KHÁCH — kể
-- cả người nhận, số điện thoại giao hàng, ghi chú cho shipper và mọi địa chỉ
-- phụ, những thứ không có bản sao ở đâu khác.
--
-- Không xoá file: nó là lịch sử đọc được của một quyết định đã bị đảo. migrate.sh
-- lọc nó khỏi cả mảng MIGRATIONS lẫn vòng cảnh báo "chưa khai", nên không có
-- đường nào script tự chạy nó.
--
-- Toàn bộ phần bên dưới là văn bản GỐC của ngày 12/09, giữ nguyên để đọc lại
-- lý lẽ khi ấy. Ba điều kiện nó liệt kê nay không còn nghĩa gì.
-- ############################################################################

-- ============================================================================
-- 2026-09-12 — BƯỚC HAI: GỠ HẲN BẢNG `addresses`
--
-- ─────────────────────────────────────────────────────────────────────────────
-- ⚠ ĐỪNG CHẠY FILE NÀY CÙNG NGÀY VỚI 2026-09-12-dia-chi-vao-ho-so.sql
--
-- Cùng lý lẽ với 2026-09-06-dot-3-go-bang-tom-tat.sql: chừng nào `addresses`
-- còn nguyên thì việc gộp địa chỉ vào hồ sơ có đường lùi THẬT — chạy file
-- QUAY-LUI rồi deploy ngược mã nguồn là sổ địa chỉ sống lại y như cũ.
--
-- Chạy file này là ĐÓNG đường lùi đó. Sau đây, quay về mã cũ nghĩa là
-- /tai-khoan?muc=dia-chi đổ lỗi 1146 "Table doesn't exist", và cách duy nhất
-- còn lại là nạp bản sao lưu.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- BA ĐIỀU KIỆN, ĐỦ CẢ BA MỚI CHẠY
--
--   1. Đã chạy 2026-09-12-dia-chi-vao-ho-so.sql và bốn câu hậu kiểm ở cuối
--      file đó đều đúng.
--
--   2. Hệ thống chạy ít nhất MỘT TUẦN với mã mới, không có báo lỗi nào liên
--      quan tới địa chỉ giao hàng — kể cả từ trang thanh toán.
--
--   3. Chạy lại câu này ngay trước khi gỡ, và nó phải ra 0:
--
--        SELECT COUNT(*) FROM addresses a
--          JOIN profiles p ON p.id = a.user_id
--         WHERE a.is_default = 1
--           AND (p.address IS NULL OR TRIM(p.address) = '');
--
--      Khác 0 nghĩa là có khách còn địa chỉ mặc định trong sổ mà hồ sơ lại
--      trống — DỪNG LẠI và chạy lại câu UPDATE ở file bước một.
--
--   4. Gỡ khối CREATE TABLE `addresses` và dòng DROP tương ứng ở đầu
--      database/schema.sql, nếu chưa làm.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- SAO LƯU TRƯỚC — NFR-R08
--
--   mysqldump -u <user> -p <ten_csdl> addresses > vin-eyewear-addresses.sql
--
-- Bảng này giữ những thứ hồ sơ KHÔNG chép sang: tên người nhận, số điện thoại
-- giao hàng, ghi chú cho shipper, nhãn địa chỉ, và mọi địa chỉ phụ. Không có
-- ngoại lệ.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- Gỡ bảng
--
-- Khoá ngoại trỏ sang `users` đi theo bảng, không cần DROP riêng. Không bảng
-- nào trỏ VÀO `addresses` — đơn hàng chép địa chỉ thành CHỮ lúc đặt chứ không
-- tham chiếu (cố ý: địa chỉ trên đơn đã giao không được đổi khi khách sửa sổ)
-- — nên không có ràng buộc nào chặn lệnh dưới đây.
-- ----------------------------------------------------------------------------
-- ⛔ LỆNH ĐÃ VÔ HIỆU HOÁ 10/09/2026 — xem khối cảnh báo ở đầu file.
--    Để nguyên dạng chú thích chứ không xoá dòng: người đọc sau này cần thấy
--    file này ĐỊNH làm gì. Ai thật sự muốn gỡ bảng thì bỏ hai dấu gạch, và khi
--    đó phải gỡ luôn AddressModel cùng khu vực "Sổ địa chỉ" của trang Hồ sơ —
--    tức là làm ngược lại UC-USER-05.
-- DROP TABLE IF EXISTS `addresses`;


-- ----------------------------------------------------------------------------
-- KIỂM TRA SAU KHI CHẠY
--
--   SHOW TABLES LIKE 'addresses';   -- không ra dòng nào
--
-- Rồi mở /tai-khoan?muc=ho-so và /thanh-toan bằng một tài khoản khách có địa
-- chỉ: cả hai phải hiện đúng như trước khi chạy.
--
-- ----------------------------------------------------------------------------
-- QUAY LUI
--
-- KHÔNG CÓ. Đó là toàn bộ lý do file này tách riêng và phải chờ một tuần.
--
-- Dựng lại bảng rỗng thì mã cũ chạy được nhưng MỌI khách đều "chưa có địa chỉ
-- nào" — tệ hơn là để nguyên, vì nó trông như dữ liệu đã mất chứ không như
-- một lỗi. Đường về duy nhất là nạp bản sao lưu tạo ở đầu file này.
-- ----------------------------------------------------------------------------
