name: 🚀 Deploy PHP Project to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Syncing PHP Code
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Quét toàn bộ để upload đủ 100% file

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./htdocs/
          protocol: ftp
          port: 21
          security: loose
          dangerous-clean-up: false
